version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
      - celery
    volumes:
      - .:/app
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app